## YAML Template.
---
spring:
    jpa:
        hibernate:
            ddl-auto: none
    datasource:
        url:jdbc: h2:file:./data/dronedb
        username: odin
        password: azgard
        driverClassName: org.h2.Driver
        
        
    h2:
        console:
            enabled: true
            path: /h2
            settings:
                trace: false
                web-allow-others: false
    sql:
        init:
            mode: always
                
server:
    contextPath: /api
    
graphql:
    servlet:
        mapping: /graphql
        actuator-metrics: true
        async-timeout: 1000
    playground:
        enabled: true
        cdn:
            enabled: false
            version: latest                